name: project_a
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  # Core
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  get_it: ^9.2.0
  # Networking & API
  dio: ^5.0.0
  google_sign_in: ^6.2.2
  url_launcher: ^6.3.2

  # Storage & Caching
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  hydrated_bloc: ^10.1.1

  # UI Components
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  multi_dropdown: ^3.0.1
  lottie: ^3.3.1
  flutter_svg: ^2.2.3
  percent_indicator: ^4.2.5
  phosphor_flutter: ^2.1.0
  readmore: ^3.0.0
  # Input & Media
  intl_phone_field: ^3.2.0
  image_picker: ^1.2.1

  # Utilities & Formatting
  intl: ^0.20.0
  logger: ^2.6.2
  flutter_dotenv: ^5.2.1
  go_router: ^17.0.0
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  
  # Localization

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/login/
    - assets/images/register/
    - assets/images/onboarding/
    - assets/images/form/
    - assets/images/profile/
    - assets/images/food/
    - assets/images/recipes/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
